# Redirects for SPA
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Environment settings
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Environment contexts
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" } 